spring.application.name: turbine
server.port: 5000

management.port: 5001
eureka.client.serviceUrl.defaultZone: http://eureka1:1111/eureka,http://eureka2:1112/eureka
turbine.combine-host-port: true
turbine.app-config: service-feign-consumer