spring.application.name: api-gateway
server.port: 8000

zuul.routes.api-hello.path: /api-hello/**
zuul.routes.api-hello.serviceId: HELLO-SERVICE

zuul.routes.api-hello-consumer.path: /api-hello-consumer/**
zuul.routes.api-hello-consumer.serviceId: service-feign-consumer

eureka.client.serviceUrl.defaultZone: http://eureka1:1111/eureka,http://eureka2:1112/eureka

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 1500
ribbon.ConnectTimeout: 1000
